#!/bin/bash

echo "enter first number"
read num1

echo "enter second number"
read num2

echo "enter third number"
read num3

if [ $num1 -eq $num2 ] && [ $num2 -eq $num3 ] && [ $num1 -eq $num3 ]; then
        echo "the number are equal"
elif [ $num1 -gt $num2 ] && [ $num1 -gt $num3 ]; then
        echo "$num1 is geater"
elif [ $num2 -gt $num3 ] && [ $num2 -gt $num1 ]; then
        echo "$num2 is geater"
else
        echo "$num3 is greater"
fi
echo $#
echo $0
echo $*
echo $@

